### ISSUE TITLE
<stdout>: hPutChar: invalid argument (invalid character)

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#285] opened 2015-05-13 20:27 UTC
When I have:
:set prompt "\x03BB> "
in global ghci.config then in EclipseFP console I get each time this message:
<stdout>: hPutChar: invalid argument (invalid character)

And it crashes there. So console became unusable. In command-line GHCi it is working well.

OS: Windows 8.1 x64

**Comment by JPMoresmau** [comment] 2015-05-13 20:31
Duplicate of #237

**Closed by JPMoresmau** 2015-05-13 20:31 UTC
