### ISSUE TITLE
Install helper executables in a single cabal install

### ISSUE THREAD

**Issue by neothemachine** [JPMoresmau/eclipsefp#272] opened 2015-02-09 16:58 UTC
I just installed a fresh ghc (7.8) and installed cabal-install freshly (1.22), I removed .ghc and .cabal before that. Then I started eclipse, told it about my new ghc and cabal, which actually was tricky for cabal, because it didn't let me save the settings as the buildwrapper entry was not set. So I put "foo" in it, saved it, then restarted eclipse to let it install the helper executables. However it looked a lot like it was installing each helper with a new cabal install command, in the same sandbox. And at one point it failed due to a version conflict. Wouldn't it be better to install everything with a single cabal install command? Also, when restarting eclipse again it automatically tried to install helpers without asking me, I think this shouldn't happen.

**Comment by JPMoresmau** [comment] 2015-02-09 17:04
Duplicate of #254, which has a discussion about installing everything in one command, etc.

**Closed by JPMoresmau** 2015-02-09 17:04 UTC
