### ISSUE TITLE
SourceGraph installation error

### ISSUE THREAD

**Issue by malteof** [JPMoresmau/eclipsefp#219] opened 2014-07-30 09:22 UTC
(I also logged this on Sourceforge, not sure which place is the correct one: https://sourceforge.net/p/eclipsefp/discussion/371922/thread/12aff122/)

Caveat: I'm completely new to Haskell, Cabal, EclipseFP.

When starting EclipseFP for the first time, it installs a bunch of packages to the sandbox but then runs into an error with SourceGraph as per below. I've tried both Windows 8.1 and Ubuntu 14.04 with latest updates applied, cabal 1.20 and otherwise the haskell-platform...

What might be wrong?

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: buildwrapper-0.8.7/installed-bd5... (user goal)
trying: graphviz-2999.17.0.1/installed-577... (user goal)
next goal: SourceGraph (user goal)
rejecting: SourceGraph-0.7.0.6 (conflict: graphviz =>
fgl==5.4.2.4/installed-159..., SourceGraph => fgl==5.5.)
rejecting: SourceGraph-0.7.0.5 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.15.0.0
&& <2999.17)
rejecting: SourceGraph-0.7.0.4 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.15.0.0
&& <2999.16)
rejecting: SourceGraph-0.7.0.3 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.14.1.0
&& <2999.15)
rejecting: SourceGraph-0.7.0.2 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz==2999.13.)
rejecting: SourceGraph-0.7.0.1 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz==2999.12.*)
rejecting: SourceGraph-0.7.0.0 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.11.0.0
&& <2999.12.0.0)
rejecting: SourceGraph-0.6.1.1 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.10.0.0
&& <2999.11.0.0)
rejecting: SourceGraph-0.6.0.2, 0.6.0.1, 0.6.0.0 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.8.0.0 &&
<2999.9.0.0)
rejecting: SourceGraph-0.5.5.0, 0.5.2.0, 0.5.1.0, 0.5.0.0 (conflict:
graphviz==2999.17.0.1/installed-577..., SourceGraph => graphviz>=2999.6.0.0 &&
<2999.7.0.0)
rejecting: SourceGraph-0.3 (conflict: buildwrapper =>
Cabal==1.16.0/installed-c6e..., SourceGraph => Cabal<1.7)
rejecting: SourceGraph-0.2, 0.1 (conflict: buildwrapper =>
Cabal==1.16.0/installed-c6e..., SourceGraph => Cabal<1.5)
Backjump limit reached (change with --max-backjumps).
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by JPMoresmau** [comment] 2015-01-04 14:37
Duplicate of #186, SourceGraph doesn't install with the rest. In the dev version SourceGraph is not installed by default.

**Closed by JPMoresmau** 2015-01-04 14:37 UTC
